### ISSUE TITLE
Multibuild & Rackspace

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj-wheels#1]
@matthew-brett, what do you need to get the permissions setup for rackspace?
@jswhit

**Comment by matthew-brett** [comment]
Can you enable this repository with travis-ci?  Then I can add the permissions.

I've done a PR with a template `.travis.yml` that needs filling in with correct details:

https://github.com/pyproj4/pyproj-wheels/pull/4

**Comment by snowman2** [comment]
Done: https://travis-ci.com/pyproj4/pyproj-wheels

**Comment by snowman2** [comment]
Thanks for getting this started!

**Comment by snowman2** [comment]
This is the current wheel manylinux wheel build process:
https://github.com/jswhit/pyproj/blob/master/build-wheels.sh

**Comment by matthew-brett** [comment]
I've added the Rackspace authentication, but I haven't attempted to put in
the build process.  That stuff would go in the `config.sh` file.

**Comment by snowman2** [comment]
This is a fantastic setup. Thanks @matthew-brett!
