### ISSUE TITLE
Windows Wheels

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj-wheels#3]
Need to determine the best way to build these. Current method has DLL load error.

**Comment by snowman2** [comment]
Current wheels built using appveyor: https://github.com/jswhit/pyproj/blob/master/appveyor.yml

**Comment by snowman2** [comment]
Issue is a DLL load failure on my machine, but I am not a windows expert by any means.

**Comment by snowman2** [comment]
Can download the most recent 2.0.1 wheel [here](https://ci.appveyor.com/api/buildjobs/5t8nqdiw2kv53lfu/artifacts/dist%2Fpyproj-2.0.1-cp36-cp36m-win_amd64.whl) for python 3.6.

**Comment by snowman2** [comment]
@ocefpaf, do you know anyone who might be able to assist building windows wheels for pyproj?

**Comment by ocefpaf** [comment]
> @ocefpaf, do you know anyone who might be able to assist building windows wheels for pyproj?

I only person I know that understands about Windows wheels builds is Christoph Gohlke but I'm not sure what is his GitHub handle.

**Comment by snowman2** [comment]
Thanks @ocefpaf, I will try sending him an email.

**Comment by snowman2** [comment]
@cgohlke are you able to share any guidance on building windows wheels?

**Comment by cgohlke** [comment]
It looks like the appveyor artifacts for `pyproj-2.0.1` are missing `proj_6_0.dll`. I usually link to static libraries.

I have not tried building Proj 6 or pyproj 2 yet.

**Comment by snowman2** [comment]
Thanks for the info, that is very helpful. I would definitely be interested in hearing more once you give building the new version a try

**Comment by cgohlke** [comment]
I built [new wheels](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj) against static PROJ 6. Seem to work. PROJ6 requires C++11, so Python 2.7 is out. Static linking requires `sqlite.lib`. I packaged data files in `pyproj\data` instead of `pyproj\proj_dir\share\proj`.

**Comment by snowman2** [comment]
@cgohlke, that is great, thanks! Do you mind sharing the build options/commands you used? 

Also, pyproj specifically looks for the data internally at `pyproj\proj_dir\share\proj`, so it won't be able to find the data internally in the new spot.

**Comment by jswhit** [comment]
conda-forge has windows builds now (https://github.com/conda-forge/pyproj-feedstock and https://github.com/conda-forge/proj.4-feedstock)

**Comment by snowman2** [comment]
Thank you @cgohlke for building the wheels for pyproj all of these years! I noticed that https://www.lfd.uci.edu/~gohlke/pythonlibs/ says it is archived. I wish you the best with whatever you are planning for the future. You have done a great service for the python Windows community :trophy:.
