### ISSUE TITLE
Move to github actions, cibuildwheel

### ISSUE THREAD

**Issue by mattip** [pyproj4/pyproj-wheels#42]
What do you think of the following ideas?:
- [] move to cibuildwheel, like [NumPy is doing](https://github.com/numpy/numpy/pull/20102) or [matlab has done](https://github.com/matplotlib/matplotlib/blob/main/.github/workflows/cibuildwheel.yml)
- [] move to github actions, which can build for [manylinux, windows, macos](https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/.github/workflows/cibuildwheel.yml#L21) and [various versions of python](https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/.github/workflows/cibuildwheel.yml#L61), build for [arm64 via qemu](https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/.github/workflows/cibuildwheel.yml#L28), and can cache the dependent libraries.
- [] this would enable adding [wheels for PyPy](https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/.github/workflows/cibuildwheel.yml#L97)

As I read the [config.sh](https://github.com/pyproj4/pyproj-wheels/blob/master/config.sh) file, your wheel building involves
- build
  - install/build support libraries sqlite 3350500, libtiff 4.3.0, nghttp2 1.43.0 and curl 7.76.1
  - install/build proj 
  - build via the normal manybuild command which could be `python -m pip wheel; python -m pip install proj*.whl`
- [test](https://github.com/pyproj4/pyproj-wheels/blob/e7209715d5e592b03ca5d817f3cfbbb6c7d996f7/config.sh#L83)
- [upload](https://github.com/pyproj4/pyproj-wheels/blob/e7209715d5e592b03ca5d817f3cfbbb6c7d996f7/.travis.yml#L115)

So I would suggest breaking this into separate PRs, like NumPy is doing:
- move to cibuildwheel/github actions with the build/test components
- add the upload step
- add aarch64, pypy builds

**Comment by snowman2** [comment]
That sounds great to me 👍

**Comment by snowman2** [comment]
Addressed with:
- https://github.com/pyproj4/pyproj/pull/1042
- https://github.com/pyproj4/pyproj/pull/1046

**Comment by mattip** [comment]
Yay
