### ISSUE TITLE
Python 3.10 wheel

### ISSUE THREAD

**Issue by EpicWink** [pyproj4/pyproj-wheels#43]
Feature request: build Python 3.10 wheel

IIRC, you can build Python 3.10rc1 wheels which will be ABI compatible with Python 3.10 runtimes, so multi-build/multibuild@13a0172  is useful

**Comment by snowman2** [comment]
Thanks for the report :+1:  Still waiting on some dependencies, so python 3.10 won't be able to be supported until those are updated.
