### ISSUE TITLE
Pyproj on M1 Mac

### ISSUE THREAD

**Issue by cygnari** [pyproj4/pyproj-wheels#46]
#### Code Sample, a copy-pastable example if possible

```python
import pyproj
```
#### Problem description

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cygnari/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "/Users/cygnari/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ImportError: dlopen(/Users/cygnari/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyproj/_network.cpython-310-darwin.so, 0x0002): tried: '/Users/cygnari/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyproj/_network.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_network.cpython-310-darwin.so' (no such file), '/usr/lib/_network.cpython-310-darwin.so' (no such file)
```

I downloaded the universal wheel so I'm not sure why it's complaining about x86 and arm issues. 

#### Expected Output

No error. 

#### Environment Information

 - Output from: `pyproj -v`: gives same error as above
 - macOS-12.1-arm64-arm-64bit
 - 3.10.0 (default, Oct 31 2021, 19:34:27) [Clang 13.0.0 (clang-1300.0.29.3)]

#### Installation method
 I installed using the pyproj-3.3.0-cp310-cp310-macosx_10_9_universal2.whl wheel on the pyproj pypi website and pip.

**Comment by snowman2** [comment]
See: https://github.com/pyproj4/pyproj/issues/1027
