### ISSUE TITLE
2.0.2 build failing

### ISSUE THREAD

**Issue by jswhit** [pyproj4/pyproj-wheels#6]
I updated BUILD_COMMIT in .travis.yml and the builds fail with this:

Worker information
hostname: d81ed8ec-8caa-4b26-bbc5-60f6aad704a9@1.production-1-worker-com-gce-1mkl
version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7
instance: travis-job-700596a5-224b-44ac-8524-e64b3612088e travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
startup: 8.59932205s
Could not fetch .travis.yml from GitHub.
/home/travis/build.sh: line 2: travis_terminate: command not found
/home/travis/build.sh: line 3: travis_cleanup: command not found
/home/travis/build.sh: line 4: travis_footer: command not found

**Comment by snowman2** [comment]
I restarted the build & also am testing the v2.0.1 tag. Fingers crossed one works :).

**Comment by snowman2** [comment]
Looks like it is working: https://travis-ci.com/pyproj4/pyproj-wheels/builds/104258205

**Comment by jswhit** [comment]
Hmmm.  Maybe a github service outage?

**Comment by snowman2** [comment]
Something like that.
