### ISSUE TITLE
Macosx wheels for 2.0.2 for python 3.6 and 3.7 missing

### ISSUE THREAD

**Issue by bjorn-spire** [pyproj4/pyproj-wheels#7]
Currently, wheels are only available for 2.7 and 3.5 but for 2.0.1 there were wheels available for 3.6 and 3.7 as well.

**2.0.2**
![2.0.2](https://user-images.githubusercontent.com/28559461/54422612-2efe2580-470f-11e9-8e63-5c0d73e39444.png)

**2.0.1**
![2.0.1](https://user-images.githubusercontent.com/28559461/54422704-58b74c80-470f-11e9-9566-4e178004de4f.png)

**Comment by snowman2** [comment]
We have the wheels, so it should be a simple fix. Thanks for the report 👍. Also, 2.1.0 will be released soon.
